<?php
// Create the content for the HTML file
$htmlContent = "<html>
<head>
<title>My HTML File</title>
</head>
<body>
<h1>Hello, World!</h1>
<p>This is my HTML file generated by PHP.</p>
</body>
</html>";

// Specify the file path and name
$filePath = "file.html";

// Open the file in write mode
$file = fopen($filePath, 'w');

// Write the HTML content to the file
fwrite($file, $htmlContent);

// Close the file
fclose($file);

echo "HTML file created successfully!";
?>
